version: "3"

services:

 server:
  tty: true
  image: kidji/te-server:latest

  container_name: te-server
  ports:
   - "5001:5001"
  networks:
   TE:
    ipv4_address: 10.12.0.3

 client:
  image: kidji/te-client:latest

  container_name: te-client
  tty: true
  ports:
   - "5000:5000"
  networks:
   TE:
    ipv4_address: 10.12.0.2


  depends_on: ["server"]
networks:
 TE:
  driver: bridge
  ipam:
   config:
    - subnet: 10.12.0.0/16