version: "3"

services:

 server:
  tty: true
  build:
    context: ./api-server/
    dockerfile: Dockerfile
  container_name: te-server
  ports:
   - "5001:5001"
  networks:
   TE:
    ipv4_address: 10.13.0.3

 client:

  build:
    context: ./api-server/
    dockerfile: Dockerfile
  container_name: te-client
  tty: true
  ports:
   - "5000:5000"
  networks:
   TE:
    ipv4_address: 10.13.0.2


  depends_on: ["server"]
networks:
 TE:
  driver: bridge
  ipam:
   config:
    - subnet: 10.13.0.0/24